### ISSUE TITLE
error TS5023: Unknown compiler option 'strictFunctionTypes'.

### ISSUE THREAD

**Issue by anweshan** [breathe/sample-watson-typescript#1]
I tried reproducing the compiler issues mentioned in your README, but upon cloning and running tsc I instead got 'error TS5023: Unknown compiler option 'strictFunctionTypes'.' ? After commenting that out I do see said compiler issues, was wondering if unknown compiler option is also an issue with watson-developer-cloud

**Comment by breathe** [comment]
Hi @anweshan -- the strictFunctionTypes option was added in typescript 2.6 I believe -- are you using an earlier version of the typescript compiler somehow -- perhaps a globally installed version or a version distributed with your ide?

This project is including typescript 2.6.2 as a devDependency so it should work if you use `npm run build` from the command-line (although its possible that some varieties of PATH customization would break this behavior).

**Comment by anweshan** [comment]
Thanks, I was using an older version of TS!
